on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Compile on release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if using Node.js, adjust if using another language)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts-iron' 
      
      - name: Install dependencies
        run: npm install

      - name: Compile project
        run: npm run build-prod 
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-project
          path: ./dist # Path to the compiled output 